butch-builddeps: various improvements
- accept more than a single package
- use butch subcommands directly
- use BINDIR
- only call butch-install if butch-deps returns a result
- add quotes for path components

diff --git a/KEEP/bin/butch-builddeps b/KEEP/bin/butch-builddeps
--- a/KEEP/bin/butch-builddeps
+++ b/KEEP/bin/butch-builddeps
@@ -1,20 +1,30 @@
 #!/bin/sh
 if [ -z "$S" ] ; then
-	echo 'S not set, did you source config?'
+	echo 'error: S not set, did you source config?'>&2
 	exit 1
 fi
 
-pkg=$1
-if [ -z "$pkg" ] ; then
+if [ -z "$1" ] || [ "$1" = "--help" ] ; then
+	echo 'usage: butch-builddeps pkg1 [...pkgN]'
 	echo 'this script installs all dependencies of a package'
 	echo '(but not the package itself).'
 	exit 1
 fi
 
-fl=$S/pkg/$pkg
-if [ ! -e "$fl" ] ; then
-	echo "package $fl does not exist!"
-	exit 1
-fi
+BINDIR="$(dirname $(readlink -f "$0"))"
 
-butch install `butch printsec "$pkg" deps`
+ec=0
+for pkg ; do
+ fl="$S"/pkg/"$pkg"
+ if [ ! -e "$fl" ] ; then
+  echo "package $fl does not exist!"
+  ec=1
+ fi
+ deps="$("$BINDIR"/butch-printsec "$pkg" deps)"
+ if [ $? != 0 ] ; then
+  ec=1
+ elif [ -n "$deps" ] ; then
+  "$BINDIR"/butch-core install `"$BINDIR"/butch-printsec "$pkg" deps`
+ fi
+done
+exit $ec
