butch-genfilelist: use sort -u
all users of the script currently do this themselves.
move it to the script so it can be handled in one place.
most of the added complexity is due to that -o pipefail was only
added to posix in 2024, so we can't rely on it being there for
few years to come.

diff --git a/KEEP/bin/butch-genfilelist b/KEEP/bin/butch-genfilelist
--- a/KEEP/bin/butch-genfilelist
+++ b/KEEP/bin/butch-genfilelist
@@ -53,7 +53,19 @@ else
 	echo "creating filelist $fl"
 	exec 3>"$fl"
 fi
-cd "$butch_install_dir"
-find . -type f -or -type l >&3
+
+cd "$butch_install_dir" || {
+	echo "error: could not cd to $butch_install_dir" >&2
+	exit 1
+}
+tmp=$(mktemp -u).$$
+trap "rm -f $tmp" INT HUP TERM
+rc=1
+if find . -type f -or -type l > "$tmp" ; then
+	rc=0
+	sort -u < "$tmp" >&3
+fi
+rm -f "$tmp"
+exit $rc
 
 
