butch-relocate: err out when symlinking fails

diff --git a/KEEP/bin/butch-relocate b/KEEP/bin/butch-relocate
--- a/KEEP/bin/butch-relocate
+++ b/KEEP/bin/butch-relocate
@@ -42,7 +42,10 @@ relocate() {
 						exit 1
 					fi
 				fi
-				ln -sf "$backlinks""$butch_install_dir"/"$dir"/"$i" "$target"
+				if ! ln -sf "$backlinks""$butch_install_dir"/"$dir"/"$i" "$target" ; then
+					echo "ERROR: could not create symlink"
+					exit 1
+				fi
 			fi
 		else
 			[ -n "$V" ] && echo "UNKNOWN object $i"
