butch-core: quote variables with paths

diff --git a/KEEP/bin/butch-core b/KEEP/bin/butch-core
--- a/KEEP/bin/butch-core
+++ b/KEEP/bin/butch-core
@@ -1,7 +1,7 @@
 #!/bin/sh
 BUTCH_VERSION=0.7.9
-test -n "$CONFIG" && . $CONFIG
-BINDIR=$(dirname $(readlink -f "$0"))
+test -n "$CONFIG" && . "$CONFIG"
+BINDIR="$(dirname $(readlink -f "$0"))"
 hlppid=
 GREP=grep
 echo ABC | $GREP ABC >/dev/null 2>&1 || GREP="busybox grep"
@@ -97,10 +97,10 @@ is_installed() {
 	return 0
 }
 dont_unlink() {
-	$AWKPROG -f $BINDIR/butch-printsec "$1" vars | $GREP -x 'no_unlink=1' >/dev/null 2>&1
+	$AWKPROG -f "$BINDIR"/butch-printsec "$1" vars | $GREP -x 'no_unlink=1' >/dev/null 2>&1
 }
 get_pkgver() {
-	ver=$($AWKPROG -f $BINDIR/butch-printsec "$1" vars | $GREP '^pkgver=')
+	ver=$($AWKPROG -f "$BINDIR"/butch-printsec "$1" vars | $GREP '^pkgver=')
 	if [ -n "$ver" ] ; then
 		printf "%s\n" "$ver" | cut -b 8-
 	else
@@ -123,15 +123,15 @@ update_butchdb() {
 	echo "$cmd $1" >&4
 	test "$2" = installed && is_tarball_pkg "$1" && return 0
 	test "$2" != installed && dont_unlink "$1" && return 0
-	rm -f $BUTCHDB.tmp
+	rm -f "$BUTCHDB".tmp
 	# if only one entry was in butch.db, and it was removed, no tmp file is created
 	# therefore we just touch it before use.
-	touch $BUTCHDB.tmp
+	touch "$BUTCHDB".tmp
 	[ -e "$BUTCHDB" ] && while read pkg_ hash_ ; do
-	test "$pkg_" = "$1" || printf "%s %s\n" "$pkg_" "$hash_" >> $BUTCHDB.tmp
-	done < $BUTCHDB
+	test "$pkg_" = "$1" || printf "%s %s\n" "$pkg_" "$hash_" >> "$BUTCHDB".tmp
+	done < "$BUTCHDB"
 	test "$2" = installed && printf "%s %s\n" "$1" "$(get_pkgver $1)" >> $BUTCHDB.tmp
-	mv $BUTCHDB.tmp $BUTCHDB
+	mv "$BUTCHDB".tmp "$BUTCHDB"
 }
 has_all_deps() {
 	echo "hasdeps $1" >&4
@@ -139,19 +139,19 @@ has_all_deps() {
 	test $resp_ = 1 && return 0 || return 1
 }
 dl_one() {
-	scrname=$B/dl_$1.sh
-	logname=$LOGPATH/dl_$1.log
+	scrname="$B"/dl_$1.sh
+	logname="$LOGPATH"/dl_$1.log
 	info "downloading $1 ($scrname) -> $logname"
-	$BINDIR/butch-merge $1 $BUTCH_DOWNLOAD_TEMPLATE > $scrname
+	"$BINDIR"/butch-merge $1 "$BUTCH_DOWNLOAD_TEMPLATE" > "$scrname"
 	test $? = 0 || {
 		echo "FAIL $1"
 		return 1
 	}
-	chmod +x $scrname
-	$scrname > $logname 2>&1 && echo "OK $1" || echo "FAIL $1"
+	chmod +x "$scrname"
+	"$scrname" > "$logname" 2>&1 && echo "OK $1" || echo "FAIL $1"
 }
 get_one() {
-	logname=$LOGPATH/dl_$1.log
+	logname="$LOGPATH"/dl_$1.log
 	info "downloading binary package $1 -> $logname"
 	fn=$(printf "%s_%s_%d\n" $1 $A $(get_pkgver $1))
 	yay=false
@@ -159,10 +159,10 @@ get_one() {
 		archive="$fn.$ext"
 		uarchive="$(printf "$archive\n" | sed 's/+/%2b/')"
 		wget "$BUTCH_BINARY_REPO"/"$uarchive" -O /tmp/"$archive" && yay=true
-		$yay && $BINDIR/butch-unpack /tmp/"$archive" || yay=false
+		$yay && "$BINDIR"/butch-unpack /tmp/"$archive" || yay=false
 		rm -f /tmp/"$archive" || true
 		$yay && break
-	done > $logname 2>&1
+	done > "$logname" 2>&1
 	$yay && echo "OK $1" || echo "FAIL $1"
 }
 start_dl() {
@@ -259,24 +259,24 @@ is_downloaded() {
 	test $resss_ = 1 && return 0 || return 1
 }
 allow_network() {
-	$AWKPROG -f $BINDIR/butch-printsec "$1" vars | $GREP -x 'need_net=1' >/dev/null 2>&1
+	$AWKPROG -f "$BINDIR"/butch-printsec "$1" vars | $GREP -x 'need_net=1' >/dev/null 2>&1
 }
 start_build() {
-	scrname=$B/build_$1.sh
-	logname=$LOGPATH/build_$1.log
+	scrname="$B"/build_$1.sh
+	logname="$LOGPATH"/build_$1.log
 	info "building $1 ($scrname) -> $logname"
-	$BINDIR/butch-merge $1 $BUTCH_BUILD_TEMPLATE > $scrname
+	"$BINDIR"/butch-merge $1 "$BUTCH_BUILD_TEMPLATE" > "$scrname"
 	test $? = 0 || {
 		echo "error: butch-merge failed"
 		exit 1
 	}
-	chmod +x $scrname
+	chmod +x "$scrname"
 	success=false
 	unsharecmd=
 	if ! allow_network "$1" ; then
 		unsharecmd="$UNSHARECMD"
 	fi
-	$unsharecmd $scrname </dev/null > $logname 2>&1 && success=true
+	$unsharecmd "$scrname" </dev/null > "$logname" 2>&1 && success=true
 	if $success ; then
 		update_butchdb "$1" installed
 	else
@@ -300,7 +300,7 @@ launch_build() {
 check_access /dev/shm w && export TMPDIR=/dev/shm
 setup_pipe "3"
 setup_pipe "4"
-(BUTCHBINDIR=$BINDIR $AWKPROG -f $BINDIR/butch-core-helper <&4 >&3) &
+(BUTCHBINDIR="$BINDIR" $AWKPROG -f "$BINDIR"/butch-core-helper <&4 >&3) &
 hlppid=$!
 
 trap "exit" INT TERM
@@ -308,7 +308,7 @@ trap "kill 0" EXIT
 
 if test $mode = outdated || test $mode = update ; then
 	args=
-	for i in $($BINDIR/butch-list) ; do
+	for i in $("$BINDIR"/butch-list) ; do
 		test ! -e "$S"/pkg/"$i" && continue
 		if test $(get_pkgver "$i") -gt $(get_pkgver_installed "$i")
 		then
@@ -368,7 +368,7 @@ for x_ in $args ; do
 	fi
 done
 
-deps=$($AWKPROG -f $BINDIR/butch-deps $args)
+deps=$($AWKPROG -f "$BINDIR"/butch-deps $args)
 test $? = 0 || die "butch deps failed"
 
 for p in $deps ; do
