butch-core/merge: do some sanity checks
if grep, sed, and awk are missing or misbehaving, havoc may happen
so we better make sure they work.

diff --git a/KEEP/bin/butch-core b/KEEP/bin/butch-core
--- a/KEEP/bin/butch-core
+++ b/KEEP/bin/butch-core
@@ -134,6 +134,10 @@ dl_one() {
 	logname=$LOGPATH/dl_$1.log
 	info "downloading $1 ($scrname) -> $logname"
 	$BINDIR/butch-merge $1 $BUTCH_DOWNLOAD_TEMPLATE > $scrname
+	test $? = 0 || {
+		echo "FAIL $1"
+		return 1
+	}
 	chmod +x $scrname
 	$scrname > $logname 2>&1 && echo "OK $1" || echo "FAIL $1"
 }
@@ -216,6 +220,10 @@ start_build() {
 	logname=$LOGPATH/build_$1.log
 	info "building $1 ($scrname) -> $logname"
 	$BINDIR/butch-merge $1 $BUTCH_BUILD_TEMPLATE > $scrname
+	test $? = 0 || {
+		echo "error: butch-merge failed"
+		exit 1
+	}
         chmod +x $scrname
 	success=false
         $scrname </dev/null > $logname 2>&1 && success=true
diff --git a/KEEP/bin/butch-merge b/KEEP/bin/butch-merge
--- a/KEEP/bin/butch-merge
+++ b/KEEP/bin/butch-merge
@@ -11,6 +11,18 @@ merges pkg with template and writes the result to stdout.
 EOF
 }
 [ -z "$2" ] && usage
+echo ABC | grep ABC >/dev/null || {
+	echo "error: grep not working!">&2
+	exit 1
+}
+test $(echo ABC | sed 's/ABC/abc/') = abc || {
+	echo "error: sed not working!">&2
+	exit 1
+}
+test $(echo "ABC abc" | $AWK '{print $2}') = abc || {
+	echo "error: awk not working!">&2
+	exit 1
+}
 pkg="$(basename "$1")"
 template="$2"
 [ -r "$S/pkg/$pkg" ] && [ -r "$2" ] || { echo "error could not read $S/pkg/$pkg and $2"; exit 1; }
