butch: re-implement butch update and add butch outdated commands
the previous update implementation in the butch C version was pretty destructive
since the user had no means of preview of what was being rebuilt and
intervention for problematic cases, or to remove specific packages from the
list.
these cases are for example when packages have conflicting files,
like in the case of busybox and wget, where when both are installed the user
usually prefers /bin/wget pointing to gnu wget.
or packages that were unlinked (possibly ncurses in favor of curses).

thus "butch update" is now an interactive process similar to "git rebase -i"
with the ability to remove things from the rebuild list and re-order items.
"butch outdated" just prints the list of outdated packages.
the old behaviour can be replicated with "butch rebuild `butch outdated`",
however it is not advisable.

diff --git a/KEEP/bin/butch-core b/KEEP/bin/butch-core
--- a/KEEP/bin/butch-core
+++ b/KEEP/bin/butch-core
@@ -1,15 +1,24 @@
 #!/bin/sh
 test -n "$CONFIG" && . $CONFIG
 BINDIR=$(dirname $(readlink -f "$0"))
+hlppid=
 timestamp() {
 	date '+%Y-%m-%d %H:%M:%S'
 }
 info() {
 	printf "%s %s\n" "$(timestamp)" "$1"
 }
+end_proc() {
+	test -n "$hlppid" && {
+		echo "QUIT" >&4
+		wait $hlppid
+		trap - EXIT
+	}
+	exit $1
+}
 die() {
 	echo "$@" >&2
-	exit 1
+	end_proc 1
 }
 usage() {
 cat << EOF
@@ -27,7 +36,9 @@ pass an arbitrary number of package names as options
                 installed
         prefetch: only download the given package and all of its dependencies,
                 unless they're not already in $C
-        <strike>update: rebuild all packages that changed since last build</strike>
+        update: rebuild packages that changed since last build
+                interactive mode, list can be edited before build start.
+	outdated: display packages that have changed since they were installed
 
 EOF
 exit 1
@@ -76,6 +87,13 @@ is_installed() {
 gethash() {
 	sha512sum "$S"/pkg/"$1" | cut -d " " -f 1
 }
+gethash_installed() {
+	echo "pkghash $1" >&4
+	read res_ <&3
+	printf "%s\n" "$res_"
+	test $res_ = 0 && return 1
+	return 0
+}
 update_butchdb() {
 	echo "INSTALLED $1" >&4
 	rm -f $BUTCHDB.tmp
@@ -121,6 +139,13 @@ setup_pipe() {
 	eval "exec $fd<> $node"
 	rm "$node"
 }
+add_list() {
+	local mylist
+	eval mylist='$'"$1"
+	test -z "$mylist" && mylist="$2" || mylist="$mylist $2"
+	eval "$1"=\""$mylist"\"
+}
+
 buildlist=
 dllist=
 dlerr=
@@ -134,15 +159,15 @@ case $1 in
 	download) mode=download; force=true;;
 	prefetch) mode=download; force=true;;
 	dl_one) mode=download_one;;
+	outdated) mode=outdated;;
+	update) mode=update;;
 	*) usage ;;
 esac
 shift
 test $mode = download_one && { dl_one "$1" ; exit $? ; }
 check_config
 args="$@"
-for x_ in $args ; do
-	test -r "$S"/pkg/"$x_" || die "$S/pkg/$x_ does not exist or no read permission!"
-done
+
 in_args() {
 	for x_ in $args ; do
 		test "$x_" = "$1" && return 0
@@ -198,9 +223,6 @@ launch_build() {
 	return 1
 }
 
-deps=$(awk -f $BINDIR/butch-deps "$@")
-test $? = 0 || die "butch deps failed"
-
 [ -z "$AWKPROG" ] && AWKPROG=awk
 if [ "$STAGE" = 0 ] ; then
 	$AWKPROG -W version 2>/dev/null | grep "mawk" > /dev/null && \
@@ -213,6 +235,60 @@ hlppid=$!
 
 trap "exit" INT TERM
 trap "kill 0" EXIT
+
+if test $mode = outdated || test $mode = update ; then
+	args=
+	for i in $($BINDIR/butch-list) ; do
+		test ! -e "$S"/pkg/"$i" && continue
+		if test $(gethash "$i") != $(gethash_installed "$i") ; then
+			add_list args "$i"
+		fi
+	done
+	if test $mode = outdated ; then
+		[ -z "$args" ] && end_proc 0
+		for i in $args ; do printf "%s\n" "$i" ; done
+		end_proc 0
+	fi
+	# update mode
+	tmp=$(mktemp -u)
+	cat <<- EOF | sed 's/ /\n/g' > $tmp
+	$args
+	EOF
+	cat <<- EOF >> $tmp
+	#
+	# welcome to butch's interactive update mode.
+	#
+	# all lines represent a package to be rebuilt, in the order of this file
+	# you may want to delete all lines with unlinked packages, or packages
+	# you do not want to rebuild for other reasons.
+	#
+	# it's also advised to reorder packages that overwrite links of others.
+	# for example, you will want to rebuild wget before busybox, so
+	# your symlinks still point to the more complete gnu wget afterwards.
+	# save this file and exit the editor when you're done.
+	#
+	# in case you don't want to change/rebuild anything, just delete all
+	# lines before saving.
+	EOF
+	[ -z "$EDITOR" ] && EDITOR=vi
+	$EDITOR $tmp
+	args=
+	while read i ; do
+		printf "%s\n" "$i" | grep -v '^#' >/dev/null 2>&1 && \
+		add_list args "$i"
+	done < $tmp
+	rm -f $tmp
+	[ -z "$args" ] && end_proc 0
+	mode=build
+	force=true
+fi
+
+for x_ in $args ; do
+	test -r "$S"/pkg/"$x_" || die "$S/pkg/$x_ does not exist or no read permission!"
+done
+
+deps=$($AWKPROG -f $BINDIR/butch-deps $args)
+test $? = 0 || die "butch deps failed"
 
 for p in $deps ; do
 	if is_installed "$p" ; then
